services:
  server:
    image: rmi_springapi_server:2.5.34
    ports:
      - 1098:1098
      - 1099:1099
    environment:
      - db.username=dbw_examples
      - db.password=dbw_examples
      - db.host=oracle_db
      - port=1098
    networks:
      - oracle_db_net
    container_name: rmi_springapi_server
      
networks:
  oracle_db_net:
    name: oracle_db_network
    external: true
