services:
  server:
    image: spring_http_remoting_server:2.5.36
    ports:
      - 12345:8080
    environment:
      - db.username=dbw_examples
      - db.password=dbw_examples
      - db.host=oracle_db
    networks:
      - oracle_db_net
    container_name: spring_http_remoting_server

networks:
  oracle_db_net:
    name: oracle_db_network
    external: true
